version: "3.8"

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    command:
      - "-promscrape.config=/etc/vm/scrape.yml"
      - "-retentionPeriod=1w"
      # опционально: снизить память/CPU или включить persistent storage
      # - "-memory.allowedPercent=60"
    ports:
      - "8428:8428"           # HTTP API (Prometheus-compatible): http://localhost:8428
    volumes:
      - ./vm/scrape.yml:/etc/vm/scrape.yml:ro
      - ./vm:/etc/vm:ro
    # для Linux, чтобы контейнер видел хост `localhost`
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
