cache:
  enabled: true
  eviction:
    policy: "lru"
    threshold: 0.9 # Когда кэш заполнен на 90% — запуск вытеснения
  storage:
    type: "malloc"
    size: "21474836480" # 20GB in bytes
  refresh:
    ttl: "1d"
    beta: "0.4"
  rules:
    - path: "/api/v2/pagedata"
      cache_key:
        query: ['project', 'stream', 'sport', 'language'] # Параметры, которые будут учавствовать в ключе кэширования
        headers: ['Accept-Encoding', 'X-Project-ID'] # Хедеры, которые будут учавствовать в ключе кэширования
      cache_value:
        headers: ['Cache-Control', 'X-Project-ID'] # Хедеры ответа, которые будут сохранены в кэше вместе с body
    - path: "/api/v1/pagecontent"
      cache_key:
        query: ['project', 'stream', 'sport', 'language'] # Параметры, которые будут учавствовать в ключе кэширования
        headers: ['Accept-Encoding', 'X-Project-ID'] # Хедеры, которые будут учавствовать в ключе кэширования
      cache_value:
        headers: ['Cache-Control', 'X-Project-ID'] # Хедеры ответа, которые будут сохранены в кэше вместе с body