cache:
  env: "prod"
  enabled: true

  logs:
    level: "info" # Any zerolog.Level.
    stats: true   # Should the statistic like num evictions, refreshes, rps, memory usage and so on be written in /std/out?

  forceGC:
    enabled: true
    interval: "10s"

  lifetime:
    max_req_dur: "100ms" # If a request lifetime is longer than 100ms then request will be canceled by context.
    escape_max_req_dur: "X-Target-Bot" # If the header exists the timeout above will be skipped.

  upstream:
    url: "https://google.com" # downstream reverse proxy host:port
    rate: 1000 # Rate limiting reqs to backend per second.
    timeout: "5s" # Timeout for requests to backend.

  preallocate:
    num_shards: 2048 # Fixed constant (see `NumOfShards` in code). Controls the number of sharded maps.
    per_shard: 768  # Preallocated map size per shard. Without resizing, this supports 2048*8196=~16785408 keys in total.
    # Note: this is an upper-bound estimate and may vary depending on hash distribution quality.

  eviction:
    threshold: 0.9 # Trigger eviction when cache memory usage exceeds 90% of its configured limit.

  storage:
    size: 32212254720 # 32GB of maximum allowed memory for the in-memory cache (in bytes).

  refresh:
    enabled: true
    ttl: "24h"
    error_ttl: "1h"
    rate: 1000 # Rate limiting reqs to backend per second.
    scan_rate: 10000 # Rate limiting of num scans items per second.
    beta: 0.4 # Controls randomness in refresh timing to avoid thundering herd (from 0 to 1).

  persistence:
    dump:
      enabled: true
      dump_dir: "public/dump"
      dump_name: "cache.dump.gz"
      max_versions: 5

  rules:
    /api/v2/pagedata:
      gzip:
        enabled: true
        threshold: 1024
      ttl: "12h"
      error_ttl: "1h"
      beta: 0.3 # Controls randomness in refresh timing to avoid thundering herd.
      cache_key:
        query: ['project[id]', 'domain', 'language', 'choice'] # Match query parameters by prefix.
        headers:
          - Accept-Encoding
          - Accept-Language
      cache_value:
        headers:
          - Content-Type
          - Content-Encoding
          - Cache-Control
          - Vary

    /api/v1/pagecontent:
      gzip:
        enabled: true
        threshold: 1024
      ttl: "36h"
      error_ttl: "3h"
      beta: 0.3 # Controls randomness in refresh timing to avoid thundering herd.
      cache_key:
        query: ['project[id]', 'domain', 'language', 'choice'] # Match query parameters by prefix.
        headers:
          - Accept-Encoding
          - Accept-Language
      cache_value:
        headers:
          - Content-Type
          - Content-Encoding
          - Cache-Control
          - Vary
